apiVersion: v1
kind: Service
metadata:
  name: ticket-intake-service
  labels:
    app: ticket-intake-service
spec:
  type: ClusterIP
  selector:
    app: ticket-intake-service
  ports:
    - name: http
      port: 80
      targetPort: 8082
      protocol: TCP
