spring:
  application:
    name: evaluation-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:1111/fire}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: ${SPRING_DATA_REDIS_PORT:2222}
      password: ${SPRING_DATA_REDIS_PASSWORD:fire123}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    properties:
      sasl:
        jaas:
          config: ${KAFKA_JAAS_CONFIG:org.apache.kafka.common.security.plain.PlainLoginModule required username="admin" password="admin";}
        mechanism: ${KAFKA_SASL_MECHANISM:PLAIN}
      security:
        protocol: ${KAFKA_SECURITY_PROTOCOL:SASL_PLAINTEXT}
    consumer:
      group-id: ${KAFKA_CONSUMER_GROUP_ID:evaluation-group}
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.value.default.type: kz.enki.fire.evaluation_service.dto.kafka.IncomingTicketMessage
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

server:
  port: 8092

app:
  kafka:
    enabled: true
    topics:
      incoming: ${APP_KAFKA_TOPICS_INCOMING:incoming_tickets}
      outgoing: ${APP_KAFKA_TOPICS_OUTGOING:final_distribution}
