apiVersion: v1
kind: ConfigMap
metadata:
  name: evaluation-service-config
data:
  datasource.url: "jdbc:postgresql://postgres:5432/fire"
  redis.host: "redis"
  redis.port: "6379"
  kafka.bootstrap-servers: "kafka:9092"
