apiVersion: v1
kind: Service
metadata:
  name: evaluation-service
  labels:
    app: evaluation-service
spec:
  type: ClusterIP
  selector:
    app: evaluation-service
  ports:
    - name: http
      port: 80
      targetPort: 8092
      protocol: TCP
